version: "3.8"
services:
  app:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
        - APP_DOMAIN=${APP_DOMAIN}
        - JWT_SECRET=${JWT_SECRET}
        - SESSION_SECRET=${SESSION_SECRET}
        - NODEMAILER_HOST=${NODEMAILER_HOST}
        - NODEMAILER_PORT=${NODEMAILER_PORT}
        - NODEMAILER_IS_SECURE=${NODEMAILER_IS_SECURE}
        - NODEMAILER_SENDER_NAME=${NODEMAILER_SENDER_NAME}
        - NODEMAILER_USER=${NODEMAILER_USER}
        - NODEMAILER_PASSWORD=${NODEMAILER_PASSWORD}
        - ORANGE_BASE_API=${ORANGE_BASE_API}
        - ORANGE_CLIENT_ID=${ORANGE_CLIENT_ID}
        - ORANGE_CLIENT_SECRET=${ORANGE_CLIENT_SECRET}
        - ORANGE_SENDER_NUMBER=${ORANGE_SENDER_NUMBER}
    restart: always
    ports:
      - ${APP_PORT}:3000
